name: Reto 4 - Aprende a usar los distintos Contextos
on:
  push:
    branches:
      - 'main' #Se activar√° si se hace push en la rama main
      
env:
  var1: Aprendiendo
  var2: Github-Actions
  var3: Contextos
jobs:
  Contexto-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: echo "${{ env.var1 }} ${{ env.var2}} ${{ env.var3}}"
  Contexto-github:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo $GITHUB_REF"
        run: echo "Desplegando en la rama $GITHUB_REF"